name: Update Semantic Scholar RSS Feeds

# Trigger: scheduled and manual
on:
  schedule:
    # Runs every day at 8:00 AM Mountain Time (15:00 UTC)
    - cron: "0 15 * * *"
  workflow_dispatch:  # <-- enables manual runs

jobs:
  update-rss:
    name: Generate and Push RSS Feeds
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate RSS feeds
        run: python generate_rss.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add rss/*.xml
          git diff --cached --quiet || git commit -m "Auto-update RSS feeds"
          git push
