name: Update Semantic Scholar RSS Feeds

on:
  schedule:
    # Runs every day at 12:00 PM UTC
    - cron: "0 12 * * *"
  workflow_dispatch: # allows manual runs from GitHub UI

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate RSS feeds
        run: |
          python generate_rss.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add rss/*.xml
          git diff --cached --quiet || git commit -m "Auto-update RSS feeds"
          git push
